### ISSUE TITLE
"Tiles" blocks use 4 quads per face

### ISSUE THREAD

**Issue by CoolMineman** [Brandcraf06/Blockus#112]
Causes CoolMineman/BitsAndChisels#60

I don't see why these textures can't just be merged into 1 quad per face. This would allow B&C compat as well as provide very small fps increases.

**Comment by Brandcraf06** [comment]
Because that's the concept of the block type:
- Visualized as small stacked color cubes that remain consistent in angles and texture.
- Directional, a standard model would make the face textures look strange.
- Reduction of the number of different textures for the different blocks.

You can still blacklist them. There is even a tag for all colored tiles if needed.
