### ISSUE TITLE
[Mod Compat] Variant Barrels (remove barrel variants completely from Blockus)

### ISSUE THREAD

**Issue by FibreTTP** [Brandcraf06/Blockus#287]
This issue requires resolution from both mods, and so has been posted to both repositories.

[Variant Barrels](https://github.com/xanthian/variantbarrels) ([CurseForge](https://curseforge.com/minecraft/mc-mods/variant-barrels-fabric)) currently detects [Blockus](https://github.com/Brandcraf06/Blockus) ([CurseForge](https://curseforge.com/minecraft/mc-mods/blockus)) and removes conflicting barrels from the game.

However, as of March 20 2022, Blockus barrel recipes have been [removed from the mod](https://github.com/Brandcraf06/Blockus/issues/223), and since Variant Barrels removes its own barrels, both sets are unobtainable (with Blockus variants requiring cheats, as only the recipe has been removed).

The best way for this to be fixed is if Variant Barrels removes compatibility for Blockus, and Blockus removes barrels from the mod entirely (there are... [issues](https://github.com/Brandcraf06/Blockus/issues/197)).

This has been tested in 1.19.2 with Blockus, EMI, Fabric API, and Variant Barrels.

View this issue at: [Variant Barrels](https://github.com/xanthian/variantbarrels/issues/11)

**Comment by Brandcraf06** [comment]
I "removed" them because they were too unstable and specialized mods for the differents containers exists and I prefer to focus on building or decorative blocks. I didn't think it would create problems like that.

So, **I'm going to completely remove the barrels from Blockus in 1.20** 
_Not in 1.19.X in case they are used in creative, they were available in the creative inventory until 1.19.3_

**Comment by FibreTTP** [comment]
That sounds fair. Best to leave the breaking changes to major version updates.
