### ISSUE TITLE
Remove out of scope quartz block decompression recipe and other 'vanilla tweak' recipes

### ISSUE THREAD

**Issue by saltyseadoggo** [Brandcraf06/Blockus#89]
Blockus adds a recipe to convert the vanilla quartz block into quartz items. My question is, ***why?*** These vanilla tweaks style recipe changes have nothing to do with the focus of this mod, which is adding building blocks, and would be much better suited to a different mod, or just a datapack, devoted to vanilla tweaks. This recipe is also a bit overpowered, as vanilla Minecraft doesn't allow quartz blocks to be decompressed to prevent one from using stonemason villager trades to break the item's intended scarcity for use in redstone parts.
This change is balance breaking and has nothing to do with the focus of Blockus, and I don't like having to choose between putting up with various little unwanted tweaks like this, #80 and #83 and not playing with Blockus at all. They aren't even listed out anywhere where end users can see what you've changed; we just discover them as surprises. Please stop making pushing these tweaky changes onto the end users. Not everyone wants them, even if you do. If you'd like, you can make a separate mod with all of these little changes in it that players can choose to use, with an actual list of them so we know what all changes you've actually made.

Preferred solution:
- Remove `blockus:quartz_from_quartz_block` for the above reasons.
- Please stop adding vanilla recipe tweaks or item model tweaks into a mod about adding new building blocks. They are better suited for a mod whose purpose is doing such things.

**Comment by Brandcraf06** [comment]
Most of these changes are from the very beginning of the mod that's why. But you are right about the models and the quartz block. However, some changes were made due to inconsistency, I'm thinking of the dried kelp as fuel or the compostable bamboo that you didn't mention. Paper as fuel as well but this is a choice to add consistency with the paper block. And rotten flesh is also part of the inconsistencies of Vanilla. But it's getting away from the focus of the mod , and I agree. However the ones mentioned above will remain exceptions (I'll consider about the rotten flesh) but for the rest you're right and I'll remove that in next update, also the textures change of some vanilla double slabs you didn't mention.

**Comment by saltyseadoggo** [comment]
Alright, good deal. One other thing is that I didn't notice the other examples that you mentioned because they aren't documented anywhere. Perhaps you could make note of the vanilla tweaks style recipes that you are keeping on the CurseForge description page somewhere, so end users are aware of them? Otherwise, we just stumble upon them by looking in REI or as one is crafting things with quartz blocks, in the case of the recipe that sparked this discussion.

I also looked into composting meat in real life to see if the rotten flesh recipe is sensible or not. I referenced [this article](https://www.gardeningknowhow.com/composting/ingredients/composting-meat-scraps.htm). It says that, while meats can be composted, they have the chance of harbouring pathogens that could contaminate the food that grows in the compost. Rotten flesh, being rotten, is likely rife with such pathogens. Just a thought.~
