### ISSUE TITLE
[Missing Features?] Some blocks don't have an effective tool and other properties

### ISSUE THREAD

**Issue by SatDog92** [Brandcraf06/Blockus#90]
A brief list of blocks that do not have an effective tool to be mined with, with an indication of what tool could be used:
- Ice bricks/Pillar/Wall (pickaxe, and not affected by Silk Touch, also, but not sure if this is intended);
- Blaze Lantern (pickaxe?);
- Snow Brick and all variants (pickaxe? no way to mine it at all, also, it's as hard as rock mined with hands with all tools. Not sure if i'm missing something but this doesn't feel right);
- White Oak Leaves (hoe, same hardness of the other leaves?);
- Thatch and Thatch Slabs/Stairs (hoe, same hardness of hay bale?);
- Sugar Block (weird case, the shovel is the effective tool but cannot be mined with hands or wrong tool without it being broken totally, it should act like sand);
- Block of Rotten Flesh (hoe or axe?);
- Membrane Block (hoe or axe?);
- Legacy Leaves (hoe? Even if it's a custom block, should it drop sticks or oak saplings as if they were oak leaves if mined without Silk Touch?)
- First Grass Block (shovel);
- Legacy Grass Block (shovel, should it be affected by Silk Touch? Should it spread to other dirt blocks? I tried to because i thought it could spread but it didn't);
- Legacy Gravel (shovel);
- Legacy Sponge (hoe);
- Dirt Path (shovel);

Then two aspects i felt like they were missing:
- shouldn't the Iron Plating Blocks and variants have the same mining sound of Lantern Block? just an idea, it's not a big deal at all;
- Shouldn't the hedges have the same drops of their respective leaves when mined without Silk Touch and be affected by Fortune?

**Comment by Brandcraf06** [comment]
Hmm indeed there are some problems so:

- Ice bricks: Completely fixed in next update, some problems with icy blocks
- Snow Bricks: The block is like a rocky variant of snow and can be mined with a pickaxe, however the hardness and resistance will be lower than stone in next update. And, obviously, the tool part problem will be fixed too.
- Blaze Lantern: The block is like a "fire version" of the sea lantern, so it uses the same properties. Sea Lantern has no effective tool assigned.
- White Oak Leaves with silk touch: Fixed for the next update
- White Oak Leaves, Thatch, Legacy Leaves, Both Legacy Grass Block, Legacy Gravel, Legacy Sponge & Path: Fixed, Blocks will have their appropriate effective tools in the next update.
- Sugar Block: Fixed for the next update
- Block of Rotten Flesh & Membrane Block: They will have the hoe as an effective tool
- Iron Plating Blocks: I don't think change the sound of the blocks

- Small Hedges: The idea would be consistent, but they will probably don't drop the same things as leaves, like apples, for some reasons. However, silk touch might be required. I will think about it.
- Legacy Leaves & Legacy Grass Blocks : The idea in "Legacy" type blocks is that they are nostalgic blocks with almost no functionality, this is kind of trophies from the history of the game. They have been added for the 10th anniversary of the game. But, I will think about it. Maybe something cool.

Thank you for reporting these problems!
